"""unique filename with path

Revision ID: 4e47bf05e9af
Revises: c2151f8a12df
Create Date: 2023-07-28 23:26:14.539111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e47bf05e9af'
down_revision = 'c2151f8a12df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique file with path', 'file', ['name', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique file with path', 'file', type_='unique')
    # ### end Alembic commands ###
