"""size field for file model

Revision ID: c2151f8a12df
Revises: 7335f88a8f47
Create Date: 2023-07-28 22:58:13.629353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2151f8a12df'
down_revision = '7335f88a8f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    # ### end Alembic commands ###
