version: '3.10'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    build: ../src/
    restart: always
    volumes:
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

volumes:
  data_value:
  media_value: